steps:
  - name: hashicorp/terraform:1.6
    id: terraform-init
    dir: terraform
    args: ["init", "-input=false"]

  - name: hashicorp/terraform:1.6
    id: terraform-apply-infra
    dir: terraform
    args: ["apply", "-auto-approve"]
    env:
      - TF_VAR_project_id=$PROJECT_ID
      - TF_VAR_region=${_REGION}
      - TF_VAR_photo_bucket_name=${_PHOTO_BUCKET}
      - TF_VAR_function_source_bucket_name=${_FUNCTION_SOURCE_BUCKET}

  - name: gcr.io/cloud-builders/gcloud
    id: zip-functions
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update
        apt-get install -y zip
        cd functions/api
        zip -r /workspace/function_api.zip .
        cd ../thumbnail
        zip -r /workspace/function_thumbnail.zip .

  - name: gcr.io/cloud-builders/gsutil
    id: upload-functions
    entrypoint: bash
    args:
      - -c
      - |
        gsutil cp /workspace/function_api.zip gs://${_FUNCTION_SOURCE_BUCKET}/function_api.zip
        gsutil cp /workspace/function_thumbnail.zip gs://${_FUNCTION_SOURCE_BUCKET}/function_thumbnail.zip

  - name: hashicorp/terraform:1.6
    id: terraform-apply-functions
    dir: terraform
    args: ["apply", "-auto-approve", "-var=enable_functions=true"]
    env:
      - TF_VAR_project_id=$PROJECT_ID
      - TF_VAR_region=${_REGION}
      - TF_VAR_photo_bucket_name=${_PHOTO_BUCKET}
      - TF_VAR_function_source_bucket_name=${_FUNCTION_SOURCE_BUCKET}

options:
  logging: CLOUD_LOGGING_ONLY
