steps:
  - name: hashicorp/terraform:1.6
    id: terraform-init
    dir: terraform
    args: ["init", "-input=false"]

  - name: hashicorp/terraform:1.6
    id: terraform-apply-infra
    dir: terraform
    args: ["apply", "-auto-approve"]
    env:
      - TF_VAR_project_id=$PROJECT_ID
      - TF_VAR_region=${_REGION}
      - TF_VAR_photo_bucket_name=${_PHOTO_BUCKET}
      - TF_VAR_function_source_bucket_name=${_FUNCTION_SOURCE_BUCKET}

  - name: gcr.io/cloud-builders/bash
    id: zip-functions
    entrypoint: bash
    args:
      - -c
      - |
        cd functions
        zip -r /workspace/functions.zip .

  - name: gcr.io/cloud-builders/gsutil
    id: upload-functions
    args:
      - cp
      - /workspace/functions.zip
      - gs://${_FUNCTION_SOURCE_BUCKET}/functions.zip

  - name: hashicorp/terraform:1.6
    id: terraform-apply-functions
    dir: terraform
    args: ["apply", "-auto-approve"]
    env:
      - TF_VAR_project_id=$PROJECT_ID
      - TF_VAR_region=${_REGION}
      - TF_VAR_photo_bucket_name=${_PHOTO_BUCKET}
      - TF_VAR_function_source_bucket_name=${_FUNCTION_SOURCE_BUCKET}

options:
  logging: CLOUD_LOGGING_ONLY
